syntax on
filetype on

au BufNewFile,BufRead *.psgi set filetype=perl

set autoindent
set expandtab
set number
set nobackup

set backspace=indent,eol,start
set tabstop=2
set softtabstop=2
set shiftwidth=2
